name: DPSLAMpy311cu126t270
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3. 11  # PyTorch 2.7.0 supports Python 3.11+
  - pytorch=2.7.0
  - pytorch-cuda=12.6
  - pytorch-mutex=1.0=cuda
  - torchvision
  - tensordict
  - nvidia/label/cuda-12.6.0::cuda-toolkit
  - nvidia/label/cuda-12.6.0::cuda-cudart
  - nvidia/label/cuda-12.6.0::cuda-nvcc
  - pyg::pytorch-scatter
  - pip:
      - tqdm
      - wandb
      - imageio
      - scipy
      - fastcore
      - albumentations
      - imagesize
      - h5py
      - gin-config
      - opencv-python
      - einops
      - numba
      - shapely
      - evo # For plotting and Multi-SLAM eval
      - matplotlib # For plotting
      - chardet # For plotting
      - PyQt5 # For plotting